{% set name = "lume-model" %}
{% set version = "3.0.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lume_model-{{ version }}.tar.gz
  sha256: c935dccf1deb4f684c4eba13e008197fa3827a6de95105ff5f89e943570b6154

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - lume-torch >=3.0.0
    - mlfow

test:
  imports:
    - lume_model
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/slaclab/lume-model
  license: SLAC Open
  license_family: OTHER
  license_file: LICENSE
  summary: Lume-model hosts the variable classes required for running LUME models.
  doc_url: https://slaclab.github.io/lume-model/
  dev_url: https://github.com/slaclab/lume-model

extra:
  recipe-maintainers:
    - pluflou
