{% set name = "lume-model" %}
{% set version = "1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slaclab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 007d6503013d7fb71705e497bdf8910218ed5776859a45894bd2d47ad1561523

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pydantic >=1.6.1,<1.8.2
    - numpy
    - pyyaml

test:
  imports:
    - lume_model
  requires:
    - pytest
  commands:
    - python -m pytest --pyargs lume_model

about:
  home: https://github.com/slaclab/lume-model
  license: SLAC Open
  license_family: OTHER
  license_file: LICENSE
  summary: Lume-model hosts the variable classes required for running LUME models.
  doc_url: https://slaclab.github.io/lume-model/
  dev_url: https://github.com/slaclab/lume-model

extra:
  recipe-maintainers:
    - jacquelinegarrahan
    - ChristopherMayes
