{% set name = "lume-model" %}
{% set version = "1.9.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lume_model-{{ version }}.tar.gz
  sha256: bc3c61994098fe6a4f55db52dc07f9965f7faa61d15563a34b257a789a73cfd1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pydantic
    - numpy
    - pyyaml
    - mlflow

test:
  imports:
    - lume_model
  requires:
    - pytest
    - botorch
    - python {{ python_min }}
  source_files:
    - tests
  commands:
    - python -m pytest --pyargs tests

about:
  home: https://github.com/slaclab/lume-model
  license: SLAC Open
  license_family: OTHER
  license_file: LICENSE
  summary: Lume-model hosts the variable classes required for running LUME models.
  doc_url: https://slaclab.github.io/lume-model/
  dev_url: https://github.com/slaclab/lume-model

extra:
  recipe-maintainers:
    - pluflou
    - ChristopherMayes
