{% set name = "lume-model" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url:  https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lume_model-{{ version }}.tar.gz
  sha256: 07a185f5096b45aac05a60ca3e17bc0bdaac7f87f894d5bc0d04a14f81c0299b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - pydantic
    - numpy
    - pyyaml

test:
  imports:
    - lume_model
  requires:
    - pytest
    - botorch <0.11
  source_files:
    - tests
  commands:
    - python -m pytest --pyargs tests

about:
  home: https://github.com/slaclab/lume-model
  license: SLAC Open
  license_family: OTHER
  license_file: LICENSE
  summary: Lume-model hosts the variable classes required for running LUME models.
  doc_url: https://slaclab.github.io/lume-model/
  dev_url: https://github.com/slaclab/lume-model

extra:
  recipe-maintainers:
    - pluflou
    - ChristopherMayes
