{% set name = "lume-model" %}
{% set version = "1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slaclab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 014fa2fabf8155bf621885a29c09fd1be222d489567def9d2faca821fcd7f223

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pydantic >=1.9.1
    - numpy
    - pyyaml

test:
  imports:
    - lume_model
  requires:
    - pytest
  commands:
    - python -m pytest --pyargs lume_model

about:
  home: https://github.com/slaclab/lume-model
  license: SLAC Open
  license_family: OTHER
  license_file: LICENSE
  summary: Lume-model hosts the variable classes required for running LUME models.
  doc_url: https://slaclab.github.io/lume-model/
  dev_url: https://github.com/slaclab/lume-model

extra:
  recipe-maintainers:
    - jacquelinegarrahan
    - ChristopherMayes
