{% set name = "lume-model" %}
{% set version = "0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slaclab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: ded757ff9254b7fb10c18d77ebc97bc479c74eb132eedcb63e42665ffaa46dca

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - pydantic >=1.6.1
    - numpy
    - pyyaml

test:
  imports:
    - lume_model
  requires:
    - pytest
  commands:
    - py.test --pyargs lume_model

about:
  home: https://github.com/slaclab/lume-model
  license: SLAC Open
  license_family: OTHER
  license_file: LICENSE
  summary: Lume-model hosts the variable classes required for running LUME models.
  doc_url: https://slaclab.github.io/lume-model/
  dev_url: https://github.com/slaclab/lume-model

extra:
  recipe-maintainers:
    - jacquelinegarrahan
    - ChristopherMayes
