{% set name = "lume-model" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slaclab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 563ad1718bc7ff94b66e61d229da44bd07d31c522c784d1f365c20afb58c3aef

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - pydantic
    - numpy
    - pyyaml

test:
  imports:
    - lume_model
  requires:
    - pytest
    - tensorflow
    - keras <3.0
    - botorch <0.11
  commands:
    - python -m pytest --pyargs tests

about:
  home: https://github.com/slaclab/lume-model
  license: SLAC Open
  license_family: OTHER
  license_file: LICENSE
  summary: Lume-model hosts the variable classes required for running LUME models.
  doc_url: https://slaclab.github.io/lume-model/
  dev_url: https://github.com/slaclab/lume-model

extra:
  recipe-maintainers:
    - pluflou
    - ChristopherMayes
