schema_version: 1

context:
  python_min: "3.11"
  version: "3.0.0"
  
package:
  name: lume-model
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/l/lume-model/lume_model-${{ version }}.tar.gz
  sha256: c935dccf1deb4f684c4eba13e008197fa3827a6de95105ff5f89e943570b6154

build:
  noarch: python
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=75.0
    - setuptools-scm
    - pip
  run:
    - python >=${{ python_min }}
    - lume-torch >=3.0.0

tests:
  - if: not win
    then:
      python:
        imports:
          - lume_model
        pip_check: true
        python_version:
          - ${{ python_min }}.*
          - "*"

about:
  homepage: https://github.com/slaclab/lume-model
  license: SLAC Open
  license_family: OTHER
  license_file: LICENSE
  summary: Lume-model hosts the variable classes required for running LUME models.
  documentation: https://slaclab.github.io/lume-model/

extra:
  recipe-maintainers:
    - pluflou
